---
- hosts: workwithme
  gather_facts: false
  tasks:
    - debug: var=hostvars[inventory_hostname] # contains most of the vars below
    - debug: var=groups # map: group name => list of members
    - debug: var=group_names # groups the current host belongs to (default: 'ungrouped')
    - debug: var=inventory_hostname
    - debug: var=inventory_hostname_short
    - debug: var=inventory_dir
    - debug: var=playbook_dir
    - debug: var=play_hosts # deprecated; beware: this is the same as ansible_play_batch
    - debug: var=ansible_play_hosts
    - debug: var=ansible_play_hosts_all # AFAIK contains unreachable hosts as well
    - debug: var=ansible_play_batch # may differ from ansible_play_hosts (think serial: 1)
    - debug: var=ansible_playbook_python

    - debug: var=ansible_config_file

    # Names of roles that are explicitly imported:
    - debug: var=ansible_play_role_names
    # Names of roles implicitly imported into the current play through
    # dependencies (meta/main.yml):
    - debug: var=ansible_dependent_role_names
    # The union of the two previous lists:
    - debug: var=ansible_role_names
    # NOTE: none of these lists of role names contains roles that have been
    # dynamically loaded through "include_role".
    - import_role:
        name: bozo

    # since Ansible 2.9.10
    - debug: var=ansible_collection
    - debug: var=ansible_role_name
