---
- hosts: localhost

  tasks:
    # Play with include vs. import and the conditional "when" to see the effects
    - include_role:
        name: bozo
      when: true
    - import_role:
        name: zorg
