---
- hosts: localhost
  tasks:

    # demonstrate the outcome of the bool filter with different inputs
    - debug:
        msg: >
          input '{{ item }}' cast to boolean is {{ item | bool }}
      with_items:
        - ""
        - " "
        - "A"
        - -1
        - 0
        - 1
        - 2
        - true
        - false
        - "true"
        - "false"
        - yes
        - no

    - name: Mind the operator precedence, pipe binds very strongly
      command: >
        /bin/echo
        My fruit is
        {{ ('banana' | length > 0) | ternary('bent', 'straight') }}

    - command: /bin/echo I do not die from an undefined variable
      when: my_undef_var | default(false)

    - set_fact:
        growing_list: "{{ growing_list | default([]) + [item, 42] }}"
      with_items:
        - A
        - B

    - set_fact:
        growing_dict: "{{ growing_dict | default({}) | combine({item: 42}) }}"
      with_items:
        - A
        - B
