---
- hosts: localhost
  tasks:

    # Demonstrate the outcome of the bool filter with different inputs.
    # See also to_bool function for implementation details:
    # https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L92
    - debug:
        msg: >
          input '{{ item }}' of type '{{ item | type_debug }}'
          cast to boolean is '{{ item | bool }}'
      with_items:
        - ""
        - " "
        - "A"
        - -1
        - 0
        - 1
        - 2
        - true
        - false
        - "true"
        - "false"
        - yes
        - no

    - debug:
        msg: Beware that bool filter on None yields None not False
      when: '{{ none | bool is none }}'

    - name: Mind the operator precedence, pipe binds very strongly
      command: >
        /bin/echo
        My fruit is
        {{ ('banana' | length > 0) | ternary('bent', 'straight') }}
      changed_when: false

    - debug:
        msg: Boolean negation has lower precedence than the pipe
      when: not x | default('y') | length > 1

    - command: /bin/echo I do not die from nested undefined data
      changed_when: false
      when: my_undef_dict.myundef_field | default(true)

    - set_fact:
        growing_list: "{{ growing_list | default([]) + [item, 42] }}"
      with_items:
        - A
        - B

    - set_fact:
        growing_dict: "{{ growing_dict | default({}) | combine({item: 42}) }}"
      with_items:
        - A
        - B

    - name: strip trailing slashes for consistent dirname and basename results
      debug:
        msg:
          path is '{{ item }}'
          dirname is '{{ item.rstrip('/') | dirname }}'
          basename is '{{ item.rstrip('/') | basename }}'
      loop:
        - ''
        - /     # Caveat: this one works better without rstrip
        - /var
        - /var/
        - /var/tmp
        - /var/tmp/
