---
- hosts: localhost
  vars:
    dyn: dynamic
    keys:
      - alpha
      - beta
      - "{{ dyn }} key"
    values:
      - eins
      - zwei
      - "{{ dyn }} val"
    mydict: "{{ dict(keys | zip(values)) }}"

  tasks:
    - debug: var=mydict
