---
- hosts: localhost

  # when using "roles" multiple calls with identical params are influenced by
  # the "allow_duplicates" setting in meta/main.yml
  roles:
    - role: bozo
      txt: Blah
    - role: bozo
      txt: Blah
    - role: hank
      txt: Hiho
    - role: hank
      txt: Hiho

  # Neither "import_role" nor "include_role" are influenced by the
  # "allow_duplicates" setting in meta/main.yml
  tasks:
    - import_role:
        name: bozo
      vars:
        txt: Blah
    - import_role:
        name: bozo
      vars:
        txt: Blah
    - import_role:
        name: hank
      vars:
        txt: Hiho
    - import_role:
        name: hank
      vars:
        txt: Hiho
