---

- name: call vicontrol
  vicontrol:
    name: jupp
    new: true

- name: veni vidi vici
  vici:
    name: caesar
    new: true
  environment:
    PATH: '/home/jjautz/.venv/ansiblelatest/bin:/usr/bin:/bin'
