---

# In my case this will be the python interpreter from the virtualenv
# that I run Ansible from.
- name: call module with default interpreter
  mymodule:
    name: jupp
    new: true

- name: call module with interpreter from customized PATH
  mymodule:
    name: whoa
    new: true
  environment:
    PATH: '/usr/bin:/bin'
# This --^ could contain the path of a virtualenv as first item
# with the effect that this module would be run in a different
# python interpreter.
