---

- name: call vicontrol
  vicontrol:
    name: jupp
    new: true

- name: veni vidi vici
  vici:
    name: caesar
    new: true
  environment:
    PATH: '/usr/bin:/bin'
# This --^ could contain the path of a virtualenv as first item
# with the effect that this module would be run in a different
# python interpreter.
